services:
  frontend:
    image: ghcr.io/lachlan2k/phatcrack/frontend:${PHATCRACK_VERSION_TAG:-latest}
    restart: unless-stopped
    environment:
      - TLS_OPTS
      - HOST_NAME
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    volumes:
      - caddy-data:/data
      ## Optional: if providing certs
      # - ./certs:/etc/caddy/Certs:ro

  api:
    image: ghcr.io/lachlan2k/phatcrack/api:${PHATCRACK_VERSION_TAG:-latest}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    user: ${PHATCRACK_USER:-root}
    environment:
      - INSECURE_ORIGIN
      - PORT=3000
      - DB_DSN=host=db user=phatcrack password=${DB_PASS:-phatcrack} dbname=phatcrack
      - FILEREPO_PATH=/srv/filerepo
      - BASE_URL=${BASE_URL:-https://${HOST_NAME}}
    volumes:
      - ./filerepo:/srv/filerepo:z

  db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U phatcrack"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=phatcrack
      - POSTGRES_PASSWORD=${DB_PASS:-phatcrack}
    volumes:
      - db-data:/var/lib/postgresql/data

  agent-server:
    image: ghcr.io/lachlan2k/phatcrack/agent-server:${PHATCRACK_VERSION_TAG:-latest}
    restart: unless-stopped

volumes:
  db-data:
  caddy-data: