version: '3'

services:
  frontend:
    image: ghcr.io/lachlan2k/phatcrack/frontend:latest
    restart: unless-stopped
    environment:
      - TLS_OPTS
      - HOST_NAME
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443

  api:
    image: ghcr.io/lachlan2k/phatcrack/api:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    user: ${PHATCRACK_USER:-root}
    environment:
      - PORT=3000
      - DB_DSN=host=db user=phatcrack password=${DB_PASS:-phatcrack} dbname=phatcrack
      - FILEREPO_PATH=/srv/filerepo
      - BASE_URL=https://${HOST_NAME}
    volumes:
      - ./filerepo:/srv/filerepo:z

  db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U phatcrack"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=phatcrack
      - POSTGRES_PASSWORD=${DB_PASS:-phatcrack}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: