version: '3'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile.webserver
    restart: unless-stopped
    environment:
      - TLS_OPTS
      - HOST_NAME
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    volumes:
      - ./certs:/etc/caddy/certs

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: unless-stopped
    environment:
      - JWT_KEY
      - PORT=3000
      - DB_DSN=host=db user=phatcrack password=${DB_PASS:-phatcrack} dbname=phatcrack

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=phatcrack
      - POSTGRES_PASSWORD=${DB_PASS:-phatcrack}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: