# This Dockerfile builds and serves the agent
FROM golang:1.21 AS builder

COPY agent /app/agent
COPY common /app/common
COPY .git /app/.git

WORKDIR /app/common
RUN go mod download -x

WORKDIR /app/agent
RUN bash build.sh

FROM caddy:2-alpine

WORKDIR /usr/share/caddy
RUN rm index.html
RUN wget -O hashcat.7z https://github.com/hashcat/hashcat/releases/download/v6.2.6/hashcat-6.2.6.7z
COPY agent/install.sh install.sh    

COPY --from=builder /app/agent/phatcrack-agent /usr/share/caddy/