version: '3'

services:
  webserver:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - DEV_API_URL=http://api:3000
    ports:
      - ${APP_PORT:-3000}:5173
    volumes:
      - ./frontend:/app:z

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - JWT_KEY=hunter2
      - PORT=3000
      - DB_DSN=host=db user=phatcrack password=${DB_PASS:-phatcrack} dbname=phatcrack
    volumes:
      - ./:/app/phatcrack:z

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=phatcrack
      - POSTGRES_PASSWORD=${DB_PASS:-phatcrack}
    volumes:
      - db-data-dev:/var/lib/postgresql/data
    ports:
      - ${DB_DEV_PORT:-5432}:5432

volumes:
  db-data-dev: