version: '3'

services:
  webserver:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - DEV_API_URL=http://api:3000
      - DEV_AGENT_SERVER_URL=http://agent-server
    ports:
      - ${APP_PORT:-3000}:5173
    volumes:
      - ./frontend:/app:z

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - PORT=3000
      - DB_DSN=host=db user=phatcrack password=${DB_PASS:-phatcrack} dbname=phatcrack
      - FILEREPO_PATH=/srv/filerepo
      - BASE_URL=http://192.168.122.1:${APP_PORT:-3000}
    volumes:
      - ./:/app/phatcrack:z
      - ./filerepo:/srv/filerepo:z

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=phatcrack
      - POSTGRES_PASSWORD=${DB_PASS:-phatcrack}
    volumes:
      - db-data-dev:/var/lib/postgresql/data
    ports:
      - ${DB_DEV_PORT:-5432}:5432

  agent-server:
    build:
      context: .
      dockerfile: Dockerfile.agent
    restart: unless-stopped

volumes:
  db-data-dev: