version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - DEV_API_URL=http://api:3000
    ports:
      - ${FE_PORT:-3000}:5173
    volumes:
      - ./frontend:/app:z

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - JWT_KEY=hunter2
      - PORT=3000
      - CORS_ALLOWED
      - MONGO_URI=mongodb://phatcrack:${DB_PASS:-phatcrack}@mongo:27017/
    volumes:
      - ./:/app/phatcrack:z
    ports:
      - ${API_PORT:-3001}:3000

  mongo:
    image: mongo:6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=phatcrack
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS:-phatcrack}
    volumes:
      - mongo-data-dev:/data/db

volumes:
  mongo-data-dev: