FROM golang:1.18

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y unzip

WORKDIR /opt/

RUN wget https://github.com/hashcat/hashcat/archive/refs/tags/v6.2.6.zip -q -O hashcat.zip
RUN unzip hashcat.zip
RUN rm hashcat.zip
RUN mv hashcat-* hashcat

WORKDIR /opt/hashcat
RUN make install_library
RUN make install_library_dev

WORKDIR /app
RUN rm -rf /opt/hashcat

RUN go install github.com/cosmtrek/air@latest

WORKDIR /app/phatcrack/api

ENTRYPOINT ["air", "main.go"]