name: Build Agent

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build Agent
      run: go build agent/main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: phatcrack-agent
        path: ./main
