on:
  release:
    types: [published]

name: Bump README

jobs:
  update-readme:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:

      - uses: actions/checkout@v3
    
      - id: get_version
        uses: battila7/get-version-action@v2
      
      - run: |
          sed -i 's@lachlan2k/phatcrack/releases/download/.*/@lachlan2k/phatcrack/releases/download/${{ steps.get_version.outputs.version }}/@' README.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "chore: Bump version in README"
          git push

    