name: Run lint checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  frontend_lint:
    name: Frontend Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint
